# Generated by Django 5.2.5 on 2026-04-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumearcion_Ventas', models.CharField(max_length=250)),
                ('Nombre_Ventas', models.CharField(max_length=50)),
                ('Categoria_ventas', models.CharField(max_length=50)),
                ('Cantidad_ventas', models.CharField(max_length=50)),
                ('Precio_ventas', models.CharField(max_length=50)),
            ],
        ),
    ]
