# Generated by Django 5.2.5 on 2026-04-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tabla_venta_delete_tabla_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd_tabla_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumearcion_Ventas', models.CharField(max_length=250)),
                ('Nombre_Ventas', models.CharField(max_length=50)),
                ('Categoria_ventas', models.CharField(max_length=50)),
                ('Cantidad_ventas', models.IntegerField()),
                ('Precio_ventas', models.CharField(max_length=50)),
                ('Fecha_ventas', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='tabla_venta',
        ),
    ]
