# Generated by Django 5.2.5 on 2026-04-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bd_tabla_venta_delete_tabla_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd_table_almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumeracion_Recepcion', models.CharField(max_length=250)),
                ('Empresa_Emision', models.CharField(max_length=250)),
                ('Nombre_Producto', models.CharField(max_length=250)),
                ('Cantidad_Producto', models.IntegerField()),
                ('Fecha_Producto', models.DateField()),
            ],
        ),
    ]
