# Generated by Django 5.2.5 on 2026-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bd_table_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd_tabla_asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumeracion_Asistencias', models.CharField(max_length=250)),
                ('Nombre_Asistencias', models.CharField(max_length=250)),
                ('Hora_Inicio_Asistencias', models.TimeField()),
                ('Hora_Final_Asistencias', models.TimeField()),
                ('Fecha_Asistencias', models.DateField()),
                ('Comentario_Asistencias', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='bd_tabla_trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumeracion_Trabajador', models.CharField(max_length=250)),
                ('Nombre_Trabajador', models.CharField(max_length=250)),
                ('Apellido_Trabajador', models.CharField(max_length=250)),
                ('Cargo_Trabajador', models.CharField(max_length=250)),
                ('Hora_Trabajador', models.IntegerField()),
                ('Fecha_Trabajador', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='bd_tabla_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enumacion_Usuario', models.CharField(max_length=250)),
                ('Nombre_Usuario', models.CharField(max_length=250)),
                ('Contrasenia_Usuario', models.CharField(max_length=250)),
                ('Correo_Usuario', models.CharField(max_length=250)),
                ('Telefono_Usuario', models.CharField(max_length=250)),
                ('Fecha_Usuario', models.DateField()),
            ],
        ),
    ]
