# Generated by Django 5.2.5 on 2026-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bd_tabla_asistencias_bd_tabla_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_tabla_asistencias',
            name='Comentario_Asistencias',
            field=models.CharField(),
        ),
    ]
