# Generated by Django 5.2.5 on 2026-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bd_tabla_asistencias_comentario_asistencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Compras_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Compras_Usuario', models.CharField(max_length=250)),
                ('Nombre_Compras_Usuario', models.CharField(max_length=250)),
                ('Cantidad_Compras_Usuario', models.IntegerField()),
                ('Precios_Compras_Usuario', models.CharField()),
                ('Fecha_Compras_Usuario', models.DateField()),
                ('Hora_compras_Usuario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Producto_Disponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Producto_Disponible', models.CharField(max_length=250)),
                ('Nombre_Producto_Disponible', models.CharField(max_length=250)),
                ('Categoria_Producto_Disponible', models.CharField(max_length=250)),
                ('Precio_Producto_Disponible', models.CharField(max_length=250)),
                ('Stock_Producto_Disponible', models.CharField(max_length=250)),
                ('Estado_Producto_Disponible', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Realizar_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Realizar_Pedido', models.CharField(max_length=250)),
                ('Nombre_Realizar_Pedido', models.CharField(max_length=250)),
                ('Dirrecion_Realizar_Pedido', models.CharField(max_length=250)),
                ('Fecha_Realizar_Pedido', models.DateField()),
                ('Hora_Realizar_Pedido', models.TimeField()),
                ('Metodo_Pago_Realizar_Pedido', models.CharField(max_length=250)),
                ('Observacion_Realizar_Pedido', models.CharField(max_length=250)),
            ],
        ),
    ]
